# /docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app
    environment:
      # This securely passes the API key from your local environment
      # into the container.
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - database

  database:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
