AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simplified Asynchronous RAG Pipeline with File Processing

Globals:
  Function:
    Timeout: 600

Parameters:
  StackName:
    Type: String
    Default: rag-app
    Description: Name of the CloudFormation stack

Resources:
  # IAM Role for Lambda functions
  ProcessingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: DynamoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['dynamodb:*']
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProcessingStatusTable}'
              - Effect: Allow
                Action: ['lambda:InvokeFunction']
                Resource: 
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*'

  # S3 Bucket for raw file uploads
  RawFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: ExpireAfter7Days
            Status: Enabled
            ExpirationInDays: 7
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  # S3 Bucket for extracted assets
  AssetsBucket:
    Type: AWS::S3::Bucket

  # DynamoDB Table for processing status
  ProcessingStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: document_key
          AttributeType: S
      KeySchema:
        - AttributeName: document_key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Layer for shared utilities
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${StackName}-common-layer"
      Description: Shared utilities for RAG pipeline
      ContentUri: src/layers/common/
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Delete

  # Step Functions State Machine
  IngestionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        Comment: "Simplified RAG Document Processing State Machine"
        StartAt: UpdateStatusProcessing
        States:
          UpdateStatusProcessing:
            Type: Task
            Resource: !GetAtt StatusUpdaterFunction.Arn
            Parameters:
              status: processing
              document_key.$: $.detail.object.key
            ResultPath: null
            Next: PartitionFile
          PartitionFile:
            Type: Task
            Resource: !GetAtt PartitioningFunction.Arn
            Parameters:
              bucket.$: $.detail.bucket.name
              key.$: $.detail.object.key
            Next: ParallelProcessing
            Catch:
              - ErrorEquals: ["States.ALL"]
                ResultPath: "$.error"
                Next: UpdateStatusError
          ParallelProcessing:
            Type: Parallel
            Branches:
              - StartAt: ProcessTextChunks
                States:
                  ProcessTextChunks:
                    Type: Map
                    Iterator:
                      StartAt: ProcessText
                      States:
                        ProcessText:
                          Type: Task
                          Resource: !GetAtt TextProcessingFunction.Arn
                          End: true
                    InputPath: "$.partition_result.texts"
                    End: true
              - StartAt: ProcessImageChunks
                States:
                  ProcessImageChunks:
                    Type: Map
                    Iterator:
                      StartAt: ProcessImage
                      States:
                        ProcessImage:
                          Type: Task
                          Resource: !GetAtt ImageProcessingFunction.Arn
                          End: true
                    InputPath: "$.partition_result.images"
                    End: true
            ResultPath: $.ProcessedData
            Next: AggregateAndSaveResults
            Catch:
              - ErrorEquals: ["States.ALL"]
                ResultPath: "$.error"
                Next: UpdateStatusError
          AggregateAndSaveResults:
            Type: Task
            Resource: !GetAtt AggregationFunction.Arn
            InputPath: $.ProcessedData
            ResultPath: null
            Next: UpdateStatusComplete
            Catch:
              - ErrorEquals: ["States.ALL"]
                ResultPath: "$.error"
                Next: UpdateStatusError
          UpdateStatusComplete:
            Type: Task
            Resource: !GetAtt StatusUpdaterFunction.Arn
            Parameters:
              status: complete
              document_key.$: $.detail.object.key
            ResultPath: null
            End: true
          UpdateStatusError:
            Type: Task
            Resource: !GetAtt StatusUpdaterFunction.Arn
            Parameters:
              status: error
              document_key.$: $.detail.object.key
            ResultPath: null
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref StatusUpdaterFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PartitioningFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref TextProcessingFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ImageProcessingFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AggregationFunction

  # EventBridge Rule to trigger Step Function on S3 uploads
  S3UploadEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger Step Function when files are uploaded to RawFilesBucket"
      EventPattern:
        source: ["aws.s3"]
        detail-type: ["Object Created"]
        detail:
          bucket:
            name: [!Ref RawFilesBucket]
          object:
            key:
              - prefix: ""
      State: ENABLED
      Targets:
        - Arn: !Ref IngestionStateMachine
          Id: "IngestionStateMachineTarget"
          RoleArn: !GetAtt EventBridgeExecutionRole.Arn

  # IAM Role for EventBridge to execute Step Functions
  EventBridgeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref IngestionStateMachine

  # Lambda Functions
  PresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/presigned_url/
      Handler: handler.lambda_handler
      Runtime: python3.10
      Role: !GetAtt ProcessingLambdaRole.Arn
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          RAW_FILES_BUCKET: !Ref RawFilesBucket
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagApi
            Path: /generate-upload-url
            Method: post

  # Heavy Partition Lambda - for all documents (with detectron2)
  PartitioningFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/partition
    Properties:
      PackageType: Image
      Timeout: 900  # 15 minutes - maximum allowed
      MemorySize: 3072  # 3GB - more headroom for detectron2
      EphemeralStorage:  # More /tmp space for large files
        Size: 2048  # 2GB temporary storage
      Role: !GetAtt ProcessingLambdaRole.Arn
      Environment:
        Variables:
          ASSETS_BUCKET: !Ref AssetsBucket

  TextProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/text_processor/
      Handler: handler.lambda_handler
      Runtime: python3.10
      Role: !GetAtt ProcessingLambdaRole.Arn
      Layers:
        - !Ref CommonLayer

  ImageProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/image_processor/
      Handler: handler.lambda_handler
      Runtime: python3.10
      Role: !GetAtt ProcessingLambdaRole.Arn
      Layers:
        - !Ref CommonLayer

  AggregationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/aggregator/
      Handler: handler.lambda_handler
      Runtime: python3.10
      Role: !GetAtt ProcessingLambdaRole.Arn
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          ASSETS_BUCKET: !Ref AssetsBucket

  StatusUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/status_updater/
      Handler: handler.lambda_handler
      Runtime: python3.10
      Role: !GetAtt ProcessingLambdaRole.Arn
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          STATUS_TABLE: !Ref ProcessingStatusTable

  GetStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_status/
      Handler: handler.lambda_handler
      Runtime: python3.10
      Role: !GetAtt ProcessingLambdaRole.Arn
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          STATUS_TABLE: !Ref ProcessingStatusTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagApi
            Path: /status/{document_key}
            Method: get

  # API Gateway
  RagApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${RagApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  RawFilesBucket:
    Description: S3 bucket for raw file uploads
    Value: !Ref RawFilesBucket
    Export:
      Name: !Sub "${AWS::StackName}-RawFilesBucket"
  
  AssetsBucket:
    Description: S3 bucket for processed assets
    Value: !Ref AssetsBucket
    Export:
      Name: !Sub "${AWS::StackName}-AssetsBucket"